dist: xenial
os: linux
language: python

install:
  - pip install tox
  - pip install codecov

script:
  - tox -r

jobs:
    include:
        - python: 3.10
          env: TOXENV=py310
        - python: 3.11
          env: TOXENV=py11
        - python: 3.12
          env: TOXENV=py12

        - python: 3.10
          env: TOXENV=style
        - python: 3.10
          env: TOXENV=coverage
        - python: 3.10
          env: TOXENV=check-manifest

after_success:
    - codecov --token=e664b805-341b-4851-95e5-c2ecfb0ac444
