dist: xenial
os: linux
language: python

install:
  - pip install tox
  - pip install codecov

script:
  - tox -r

jobs:
    include:
        - python: 3.7
          env: TOXENV=py37
        - python: 3.8
          env: TOXENV=py38

        - python: 3.8
          env: TOXENV=style
        - python: 3.8
          env: TOXENV=coverage
        - python: 3.7
          env: TOXENC=check-manifest

after_success:
    - codecov --token=e664b805-341b-4851-95e5-c2ecfb0ac444
